routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'role'], function () {
    Route::get('/', function() {
        return redirect('/home');
    });
});

Route::get('/signin', function () {
    return view('auth.login');
});


Route::resource('login', 'LoginController');



Route::get('logout', 'LoginController@logout')->name('logout');

//Route::get('/earnings','AdminController@earnings');



Route::group(['middleware' => 'admin'], function () {
    Route::get('/register','RegistrationController@register')->name('register');
    Route::post('register', 'RegistrationController@store')->name('register.store');
    Route::resource('role', RoleController::class);
    Route::resource('tutoriel', TutorielController::class);
    Route::resource('questionnaire', QuestionnairesController::class);
    Route::get('reponse','ReponseController@index')->name('reponse.index');
    Route::post('supprimer/{id}','ReponseController@destroy')->name('reponse.destroy');
    Route::post('reponse/users','ReponseController@show')->name('reponse.show');
    Route::post('reponse/stat/search','ReponseController@showstat')->name('reponse.showstat');
    Route::post('reponse/heureU','ReponseController@showHeureAndU')->name('reponse.showHeureAndU');
    Route::get('reponse/stat','ReponseController@stat')->name('reponse.stat');
    route::get('user','usersController@lists')->name('listusers');
    Route::post('supp/{id}','AdminController@destroy')->name('admin.destroy');
    Route::post('resetP','AdminController@resetP')->name('resetP');
    Route::resource('solution', SolutionController::class);
});

Route::group(['middleware' => 'users'], function () {
    Route::get('/changePassword','usersController@changePassword')->name('changePassword');
    Route::get('/home','usersController@home')->name('home');
    Route::post('/Password','usersController@Password')->name('Password');
    Route::resource('users', 'usersController');
    Route::post('update/','ReponseController@update')->name('reponse.update');
    Route::post('users','ReponseController@store')->name('reponse.store');
    Route::get('/tutoriels', 'TutorielController@list');
    Route::get('/tutoriels/{id}', 'TutorielController@show')->name('tutoriels.view');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email',
        'password',
        'das',
        'prenom',
        'nom',
        'pole',
        'projet',
        'jour',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/usersController.php
<?php

namespace App\Http\Controllers;

use Cartalyst\Sentinel\Users\EloquentUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Questionnaires;
use App\solution;
use App\reponse;
use Illuminate\Support\Facades\Log;
use Sentinel;

class usersController extends Controller
{
    public function index(){
        $users=  Sentinel::getUser();
        $user_id=Sentinel::getUser()->id;
        $questionnaires = Questionnaires::all();
        $solutions = solution::all();
        $reponses =reponse::where('user_id', $user_id)->get();;
        return view('users.tasks')->with(['questionnaires'=>$questionnaires])->with(['users'=>$users])->with(['solutions'=>$solutions])->with(['reponses'=>$reponses]);
    }

    public function home(){
        $users=  Sentinel::getUser();
        $user_id=Sentinel::getUser()->id;
        $questionnaires = Questionnaires::all();
        $solutions = solution::all();
        #$reponses = reponse::where('user_id', $user_id)->get();
        $reponses = reponse::join('questionnaires', 'reponses.question_id', '=', 'questionnaires.id')->where('user_id', $user_id)->get();
        return view('users.home')->with(['questionnaires'=>$questionnaires])->with(['users'=>$users])->with(['reponses'=>$reponses]);
    }

    public function changePassword(){
        return view('users.changepassword');
    }
    public function Password(Request $request){
        Sentinel::authenticate($request->all());
        $password= Sentinel::getUser()->password;

        if(hash::check($request->get('current-password'), $password)){
//Current password dont match

            if(strcmp($request->get('current-password'), $request->get('new-password')) == 0){
//Current password and new password are same
                return redirect()->back()->with("error","New Password cannot be same as your current password. Please choose a different password.");
            }

//Change Password
            $users =  Sentinel::getUser();
            $users->password = bcrypt($request->get('new-password'));
            $users->save();
            return redirect()->back()->with("success","Password changed successfully !");

        }else{
            return redirect()->back()->with("error","mot de passe actuelle incorrect.");

        }


    }
    public function lists()
    {
        $users = EloquentUser::join('role_users', 'users.id', '=', 'role_users.user_id')
            ->get();
        Log::debug($users);
        return view('users.lists')->with(['users' => $users]);
    }

    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $users = $request->all();
        $input = user::create($users);
        if ($input) {
            return redirect()->route('users.lists')->with(['success'=>'Collaborateur ajouté(e)']);
        } else {
            return redirect()->route('users.lists')->with(['error'=>'utilisateur non ajouté(e) ']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $users = user::find($id);
        $users->update($request->all());
        if (sizeof($users)) {
            return response()->json([
                'user' => $users
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }

}

resources/views/users/changepassword.blade.php
@extends('layout.dashboard')
@section('section')
    <br><br><br><br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Changer Mot de passe</div>
                    <div class="panel-body">
                        @if (session('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                        @endif
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif
                        <form class="form-horizontal" method="POST" action="{{ route('Password') }}">
                            {{ csrf_field() }}
                            <div class="form-group{{ $errors->has('current-password') ? ' has-error' : '' }}">
                                <label for="new-password" class="col-md-4 control-label">Mot de passe actuel</label>
                                <div class="col-md-6">
                                    <input id="current-password" type="password" class="form-control" name="current-password" required>
                                    @if ($errors->has('current-password'))
                                        <span class="help-block">
<strong>{{ $errors->first('current-password') }}</strong>
</span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('new-password') ? ' has-error' : '' }}">
                                <label for="new-password" class="col-md-4 control-label">Nouveau Mot de passe</label>
                                <div class="col-md-6">
                                    <input id="new-password" type="password" class="form-control" name="new-password" required>
                                    @if ($errors->has('new-password'))
                                        <span class="help-block">
<strong>{{ $errors->first('new-password') }}</strong>
</span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="new-password-confirm" class="col-md-4 control-label">Confirmer Nouveau Mot de passe</label>
                                <div class="col-md-6">
                                    <input id="new-password-confirm" type="password" class="form-control" name="new-password_confirmation" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Changer Mot de passe
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/create.blade.php
@extends('layout.dashboard')
@section('section')
    <div><!-- page -->
        <nav class="top-bar clearfix">
            <div class="container-fluid clearfix">
                <a class="top-bar-brand" href="#">
                    <span class="atosIconFont atosIconFont-logo"></span>
                </a>
                <!-- <span>Production</span> -->
            </div>
        </nav>
        <div class="clearfix contentsso pki" users="main" style="margin-top: 105.25px;"><!-- content -->
            <div class="clearfix sso-box">
                <div class="wg-pki">
                    {!! Form::open(['route' => 'users.store']) !!}
                    <fieldset>
                        <label>Prénom</label>
                        <input type="text" name="slug"  required>
                        <label>Nom</label>
                        <input type="text" name="name" required>
                        {{--                        <input type="submit" class="btn btn-block" value="Se connecter" onclick="validateForm('dataForm', this)">--}}
                        {!! Form::submit('Save',['class'=>'btn btn-block']) !!}
                    </fieldset>
                    {!! Form::close() !!}
                </div>
            </div>
        </div><!-- /content -->
    </div><!-- /page -->





    {{-- <div class="row-fluid">
         <div class="span6">
             <div class="widget-box">
                 <div class="widget-title"><span class="icon"> <i class="icon-align-justify"></i> </span>
                     <h5>Crée Role</h5>
                 </div>
                 <div class="widget-content nopadding">
                     {!! Form::open(['route' => 'role.store','class'=>'form-horizontal']) !!}
                     <div class="control-group">
                         <label class="control-label">Slug</label>
                         <div class="controls">
                             <input type="text" name="slug" class="colorpicker input-big span11"
                                    placeholder="Titre" required>
                             {{$errors->first('slug')}}
                         </div>
                         <div class="control-group">
                             <label class="control-label">Name</label>
                             <div class="controls">
                                 <input type="text" required name="name"placeholder="name"
                                        class="colorpicker input-big span11">
                                 {{$errors->first('name')}}
                         </div>

                         <div class="form-actions">
                             {!! Form::submit('Save',['class'=>'btn btn-success']) !!}
                             <a href="{{route('role.index')}}" class="btn btn-danger">Cancel</a>
                         </div>
                     </div>
                     {!! Form::close() !!}
                 </div>
             </div>
         </div>
     </div>
     </div>--}}
@stop

resources/views/users/edit.blade.php
@extends('layout.dashboard')
@section('section')
    <div class="row-fluid">
        <div class="span6">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>Enregistrement Etat</h5>
                </div>
                <div class="widget-content nopadding">
                    {{Form::model($etat,[
                                   'method'=>'patch','class'=>'form-horizontal',
                                   'route'=>['etat.update',$etat->id]
                               ])}}
                    <div class="control-group">
                        <label class="control-label">Titre</label>
                        <div class="controls">
                            <input type="text" value="{{$etat->title}}" name="title" class="colorpicker input-big span11"
                                   placeholder="Titre" required>
                            {{$errors->first('title')}}
                        </div>
                        <div class="control-group">
                            <label class="control-label">Couleur (hex)</label>
                            <div class="controls">
                                <input type="color" required name="colors" data-color="#ffffff" value="{{$etat->colors}}"
                                       class="colorpicker input-big span11">
                                {{$errors->first('colors')}}
                                <span class="help-block">Couleur picker au Format (hex)</span></div>
                        </div>

                        <div class="form-actions">
                            {!! Form::submit('Save',['class'=>'btn btn-success']) !!}
                            <a href="{{route('etat.index')}}" class="btn btn-danger">Cancel</a>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    </div>
@stop

resources/views/users/lists.blade.php
@extends('layout.dashboard')
@section('section')
    <div class="container-fluid">
        <hr>
        <div class="row-fluid">
            <div class="span12">
                <a class="btn btn-primary icon-plus-sign pull-right" href="{{route('register')}}"> Nouveau collaborateur</a>
                <div class="widget-box">
                    <div class="widget-title"><span class="icon"> <i class="icon-th"></i> </span>
                        <h5> <u>Liste des collaborateurs de Worldline d'Atos SN </u></h5>
                    </div>
                    <div class="widget-content nopadding">
                        <table class="table table-bordered table-striped">
                            <h3>ADMINS</h3>
                            <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Prénom</th>
                                <th>Das</th>
                                <th>E-mail</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                            @foreach($users as $user)
                                @if($user->role_id == 1)
                                <tbody>
                                <tr class="odd gradeX">

                                    <td>{{$user->prenom}}</td>
                                    <td>{{$user->nom}}</td>
                                    <td>
                                        {{$user->das}}
                                    </td>
                                    <td>{{$user->email}}</td>
{{--                                    <td>{{$user->options}}</td>--}}
                                    <td>{{$user->options}}
                                        <a href="#myAlert{{$user->id}}" data-toggle="modal"
                                           class="btn btn-danger btn-mini">Retirer les droits de connexion</a>

{{--                                        <a class="btn btn-info btn-mini" href="{{route('users.edit',$user->id)}}">Modifier</a>--}}
                                        <div id="myAlert{{$user->id}}" class="modal " style="width: fit-content ; background-color: white;position: fixed; margin-left: auto">
                                            <div class="modal-header">
                                                <button data-dismiss="modal" class="close" type="button">×</button>
                                                <h3>Attention</h3>
                                            </div>
                                            <div class="modal-body">
                                                <p>Voulez vous vraiment retirer ce collaborateur?</p>
                                            </div>
                                            <div class="modal-footer">
                                                {{Form::open([
                                      'method'=>'post',
                                      'route'=>['admin.destroy',$user->id] ])}}
                                                {{Form::button('Confirmer', array('type' => 'submit', 'class' => 'btn btn-primary'))}}
                                                <a data-dismiss="modal" class="btn" href="#">Cancel</a></div>
                                            {{Form::close()}}
                                        </div>


                                    </td>
                                </tr>
                                </tbody>
                                @endif
                            @endforeach
                        </table>
                        <br><br><br>
                        <table class="table table-bordered table-striped">
                            <h3>COLLABORATEURS</h3>
                            <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Prénom</th>
                                <th>Das</th>
                                <th>E-mail</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                            @foreach($users as $user)
                                @if($user->role_id == 2)
                                    <tbody>
                                    <tr class="odd gradeX">

                                        <td>{{$user->prenom}}</td>
                                        <td>{{$user->nom}}</td>
                                        <td>
                                            {{$user->das}}
                                        </td>
                                        <td>{{$user->email}}</td>
                                        {{--                                    <td>{{$user->options}}</td>--}}
                                        <td>{{$user->options}}
                                            <a href="#myAlert{{$user->id}}" data-toggle="modal"
                                               class="btn btn-danger btn-mini">Retirer les droits de connexion</a> <br>
                                            <a href="#myAlert{{$user->id}}2" data-toggle="modal"
                                               class="btn btn-info btn-mini">Reinitialiser le mot de passe</a>

                                            {{Form::open([
                                          'method'=>'post',
                                          'route'=>['reponse.show'] ])}}
                                            <input type="hidden" name="user_id" value="{{$user->id}}">
                                            {{Form::button('Voir les reponses aux questionnaires', array('type' => 'submit', 'class' => 'btn btn-primary'))}}
                                            {{Form::close()}}
                                            {{--                                        <a class="btn btn-info btn-mini" href="{{route('users.edit',$user->id)}}">Modifier</a>--}}
                                            <div id="myAlert{{$user->id}}" class="modal " style="width: fit-content ; background-color: white;position: fixed; margin-left: auto">
                                                <div class="modal-header">
                                                    <button data-dismiss="modal" class="close" type="button">×</button>
                                                    <h3>Attention</h3>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Voulez vous vraiment retirer ce collaborateur?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    {{Form::open([
                                          'method'=>'post',
                                          'route'=>['admin.destroy',$user->id] ])}}
                                                    {{Form::button('Confirmer', array('type' => 'submit', 'class' => 'btn btn-primary'))}}
                                                    <a data-dismiss="modal" class="btn" href="#">Cancel</a></div>
                                                {{Form::close()}}
                                            </div>

                                            <div id="myAlert{{$user->id}}2" class="modal " style="width: fit-content ; background-color: white;position: fixed; margin-left: auto">
                                                <div class="modal-header">
                                                    <button data-dismiss="modal" class="close" type="button">×</button>
                                                    <h3>Attention</h3>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Voulez vous vraiment reinitialiser?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    {{Form::open([
                                          'method'=>'post',
                                          'route'=>['resetP'] ])}}
                                                    <input type="hidden" name="user_id" value="{{$user->id}}">
                                                    <input type="hidden" name="prenom" value="{{$user->prenom}}">
                                                    <input type="hidden" name="nom" value="{{$user->nom}}">
                                                    <input type="hidden" name="email" value="{{$user->email}}">
                                                    <label> Mot de passe temporaire  <input type="text" name="pwd" required></label>


                                                    {{Form::button('Confirmer', array('type' => 'submit', 'class' => 'btn btn-primary'))}}
                                                    <a data-dismiss="modal" class="btn" href="#">Cancel</a></div>
                                                {{Form::close()}}
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                @endif
                                    @endforeach
                        </table>
                        <br><br><br><br><br><br><br><br><br><br><br><br>
                    </div>
                </div>
                <div class="pagination alternate">

                    <ul class="pagination pull-right">
                        <li class="">#</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@stop