routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'role'], function () {
    Route::get('/', function() {
        return redirect('/home');
    });
});

Route::get('/signin', function () {
    return view('auth.login');
});


Route::resource('login', 'LoginController');



Route::get('logout', 'LoginController@logout')->name('logout');

//Route::get('/earnings','AdminController@earnings');



Route::group(['middleware' => 'admin'], function () {
    Route::get('/register','RegistrationController@register')->name('register');
    Route::post('register', 'RegistrationController@store')->name('register.store');
    Route::resource('role', RoleController::class);
    Route::resource('tutoriel', TutorielController::class);
    Route::resource('questionnaire', QuestionnairesController::class);
    Route::get('reponse','ReponseController@index')->name('reponse.index');
    Route::post('supprimer/{id}','ReponseController@destroy')->name('reponse.destroy');
    Route::post('reponse/users','ReponseController@show')->name('reponse.show');
    Route::post('reponse/stat/search','ReponseController@showstat')->name('reponse.showstat');
    Route::post('reponse/heureU','ReponseController@showHeureAndU')->name('reponse.showHeureAndU');
    Route::get('reponse/stat','ReponseController@stat')->name('reponse.stat');
    route::get('user','usersController@lists')->name('listusers');
    Route::post('supp/{id}','AdminController@destroy')->name('admin.destroy');
    Route::post('resetP','AdminController@resetP')->name('resetP');
    Route::resource('solution', SolutionController::class);
});

Route::group(['middleware' => 'users'], function () {
    Route::get('/changePassword','usersController@changePassword')->name('changePassword');
    Route::get('/home','usersController@home')->name('home');
    Route::post('/Password','usersController@Password')->name('Password');
    Route::resource('users', 'usersController');
    Route::post('update/','ReponseController@update')->name('reponse.update');
    Route::post('users','ReponseController@store')->name('reponse.store');
    Route::get('/tutoriels', 'TutorielController@list');
    Route::get('/tutoriels/{id}', 'TutorielController@show')->name('tutoriels.view');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $table = 'roles';

    protected $fillable = [
        'slug', 'name'
    ];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::paginate(5);
        return view('role.index')->with(['roles' => $roles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('role.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $role = $request->all();
        $input = Role::create($role);
        if ($input) {
            return redirect()->route('role.index')->with(['success'=>'role crée']);
        } else {
            return redirect()->route('role.index')->with(['error'=>'role non crée ']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::find($id);
        $role->update($request->all());
        if (sizeof($role)) {
            return response()->json([
                'role' => $role
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::find($id);
        if ($role) {
            $role->delete();
            return redirect()->back()->with("success","Role supprimer");
        } else {
            return redirect(404);
        }
    }
}

resources/views/role/create.blade.php
@extends('layout.dashboard')
@section('section')
    <div><!-- page -->
        <nav class="top-bar clearfix">
            <div class="container-fluid clearfix">
                <a class="top-bar-brand" href="#">
                    <span class="atosIconFont atosIconFont-logo"></span>
                </a>
                <!-- <span>Production</span> -->
            </div>
        </nav>
        <div class="clearfix contentsso pki" role="main" style="margin-top: 105.25px;"><!-- content -->
            <div class="clearfix sso-box">
                <div class="wg-pki">
                    {!! Form::open(['route' => 'role.store']) !!}
                    <fieldset>
                         <label>Slug</label>
                        <input type="text" name="slug"  required>
                        <label>Nom</label>
                        <input type="text" name="name" required>
                        {{--                        <input type="submit" class="btn btn-block" value="Se connecter" onclick="validateForm('dataForm', this)">--}}
                        {!! Form::submit('Save',['class'=>'btn btn-block']) !!}
                    </fieldset>
                    {!! Form::close() !!}
                </div>
            </div>
        </div><!-- /content -->
    </div><!-- /page -->
@stop

resources/views/role/edit.blade.php
@extends('layout.dashboard')
@section('section')
    <div class="row-fluid">
        <div class="span6">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>Enregistrement Etat</h5>
                </div>
                <div class="widget-content nopadding">
                    {{Form::model($etat,[
                                   'method'=>'patch','class'=>'form-horizontal',
                                   'route'=>['etat.update',$etat->id]
                               ])}}
                    <div class="control-group">
                        <label class="control-label">Titre</label>
                        <div class="controls">
                            <input type="text" value="{{$etat->title}}" name="title" class="colorpicker input-big span11"
                                   placeholder="Titre" required>
                            {{$errors->first('title')}}
                        </div>
                        <div class="control-group">
                            <label class="control-label">Couleur (hex)</label>
                            <div class="controls">
                                <input type="color" required name="colors" data-color="#ffffff" value="{{$etat->colors}}"
                                       class="colorpicker input-big span11">
                                {{$errors->first('colors')}}
                                <span class="help-block">Couleur picker au Format (hex)</span></div>
                        </div>

                        <div class="form-actions">
                            {!! Form::submit('Save',['class'=>'btn btn-success']) !!}
                            <a href="{{route('etat.index')}}" class="btn btn-danger">Cancel</a>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    </div>
@stop

resources/views/role/index.blade.php
@extends('layout.dashboard')
@section('section')
    <div class="container-fluid">
        <hr>
        <div class="row-fluid">
            <div class="span12">
                {{--        <a class="btn btn-primary icon-plus-sign pull-right" href="{{route('role.create')}}"> Nouveau Role</a> --}}
                       <div class="widget-box">
                           <div class="widget-title"><span class="icon"> <i class="icon-th"></i> </span>
                               <h5><u>Roles</u></h5>
                           </div>
                           <div class="widget-content nopadding">
                               <table class="table table-bordered table-striped">
                                   <thead>
                                   <tr>
                                       <th>Slug</th>
                                       <th>Name</th>
                                       {{--     <th>Options</th> --}}
                                       </tr>
                                       </thead>
                                       @foreach($roles as $role)
                                           <tbody>
                                           <tr class="odd gradeX">
                                               <td>{{$role->slug}}</td>
                                               <td>
                                                  {{$role->name}}
                                               </td>
                                               <td>
                                                   {{--      <a href="#myAlert{{$role->id}}" data-toggle="modal"
                                                           class="btn btn-danger btn-mini">Supprimer</a>
                {{--                                        <a class="btn btn-info btn-mini" href="{{route('role.edit',$role->id)}}">Modifier</a>--}}
                                        <div id="myAlert{{$role->id}}" class="modal " style="width: fit-content ; background-color: white;position: relative;">
                                            <div class="modal-header">
                                                <button data-dismiss="modal" class="close" type="button">×</button>
                                                <h3>Attention</h3>
                                            </div>
                                            <div class="modal-body">
                                                <p>Voulez vous vraiment supprimer ce role</p>
                                            </div>
                                            <div class="modal-footer">
                                                {{Form::open([
                                           'method'=>'delete',
                                           'route'=>['role.destroy',$role->id] ])}}
                                                {{Form::button('Confirmer', array('type' => 'submit', 'class' => 'btn btn-primary'))}}
                                                <a data-dismiss="modal" class="btn" href="#">Cancel</a></div>
                                            {{Form::close()}}
                                        </div>

                                    </td>
                                </tr>
                                </tbody>
                            @endforeach
                        </table>
                        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
                    </div>
                </div>
                <div class="pagination alternate">

                    <ul class="pagination pull-right">
                        <li class="">{{$roles->links()}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@stop