routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'role'], function () {
    Route::get('/', function() {
        return redirect('/home');
    });
});

Route::get('/signin', function () {
    return view('auth.login');
});


Route::resource('login', 'LoginController');



Route::get('logout', 'LoginController@logout')->name('logout');

//Route::get('/earnings','AdminController@earnings');



Route::group(['middleware' => 'admin'], function () {
    Route::get('/register','RegistrationController@register')->name('register');
    Route::post('register', 'RegistrationController@store')->name('register.store');
    Route::resource('role', RoleController::class);
    Route::resource('tutoriel', TutorielController::class);
    Route::resource('questionnaire', QuestionnairesController::class);
    Route::get('reponse','ReponseController@index')->name('reponse.index');
    Route::post('supprimer/{id}','ReponseController@destroy')->name('reponse.destroy');
    Route::post('reponse/users','ReponseController@show')->name('reponse.show');
    Route::post('reponse/stat/search','ReponseController@showstat')->name('reponse.showstat');
    Route::post('reponse/heureU','ReponseController@showHeureAndU')->name('reponse.showHeureAndU');
    Route::get('reponse/stat','ReponseController@stat')->name('reponse.stat');
    route::get('user','usersController@lists')->name('listusers');
    Route::post('supp/{id}','AdminController@destroy')->name('admin.destroy');
    Route::post('resetP','AdminController@resetP')->name('resetP');
    Route::resource('solution', SolutionController::class);
});

Route::group(['middleware' => 'users'], function () {
    Route::get('/changePassword','usersController@changePassword')->name('changePassword');
    Route::get('/home','usersController@home')->name('home');
    Route::post('/Password','usersController@Password')->name('Password');
    Route::resource('users', 'usersController');
    Route::post('update/','ReponseController@update')->name('reponse.update');
    Route::post('users','ReponseController@store')->name('reponse.store');
    Route::get('/tutoriels', 'TutorielController@list');
    Route::get('/tutoriels/{id}', 'TutorielController@show')->name('tutoriels.view');
});

app/Questionnaires.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Questionnaires extends Model
{
    protected $table = 'questionnaires';

    protected $fillable = [
        'title', 'type', 'content', 'mauvais', 'solution'
    ];
}

app/Http/Controllers/QuestionnairesController.php
<?php

namespace App\Http\Controllers;

use App\Questionnaires;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class QuestionnairesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questionnaires = Questionnaires::orderBy('title', 'asc')->orderBy('id', 'asc')->get();
        return view('questionnaires.index')->with(['questionnaires'=>$questionnaires]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('questionnaires.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $listQuestionnaires =Questionnaires::all();
        $questionnaire = Questionnaires::create($request->all());
        if ($questionnaire){
            return redirect()->route('questionnaire.index')->with(['questionnaires'=>$listQuestionnaires]);
        }else{
            return redirect()->route('questionnaire.create')->with(['error'=>'Erreur lors de l\'enregistrement du questionnaire']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $questionnaire = Questionnaires::find($id);
        return view('answers.create')->with(['questionnaire'=>$questionnaire]);
          //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $questionnaire = Questionnaires::find($id);
        return view('questionnaires.edit')->with(['questionnaire'=>$questionnaire]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $qustionnaire = Questionnaires::find($id);
        $qustionnaire->update($request->all());
        return redirect()->route('questionnaire.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $questionnaire = questionnaires::find($id);
        if ($questionnaire) {
            $questionnaire->delete();
            return redirect()->back()->with("success","question supprimer");
        } else {
            return redirect(404);

        } //
    }
}

resources/views/questionnaires/create.blade.php
@extends('layout.dashboard')
@section('section')
    <div><!-- page -->
        <nav class="top-bar clearfix">
            <div class="container-fluid clearfix">
                <a class="top-bar-brand" href="#">
                    <span class="atosIconFont atosIconFont-logo"></span>
                </a>
                <!-- <span>Production</span> -->
            </div>
        </nav>
        <div class="clearfix contentsso pki" role="main" style="margin-top: 105.25px;"><!-- content -->
            <div class="clearfix sso-box">
                <div class="wg-pki">
                    {!! Form::open(['route' => 'questionnaire.store']) !!}
                    <fieldset>
                        <label>Titre</label>
                        <select name="title" required>
                            <option value="Bureautique">Bureautique</option>
                            <option value="Acces Atos">Acces Atos</option>
                            <option value="Acces WL">Acces wl</option>
                            <option value="lenteur">Lenteur</option>
                            <option value="Boite Mail">Configuration boite WL</option>
                            <option value="autres">Autres</option>
                        </select>
                        <br>
                        <label>Type</label>
                        <select name="type" id="type" onchange="changedType();" required>
                            <option value="1">Question ferme</option>
                            <option value="0">Question ouverte </option>
                        </select>
                        <br>
                        <label>Réponse problematique (A afficher)</label>
                        <select name="mauvais" id="mauvais" required>
                            <option value="1">Oui</option>
                            <option value="0">Non</option>
                        </select>
                        <br>
                        <label>Contenu</label>
                        <input type="text" style="width: 50%" name="content" required>
                        <br>
                        <label>Solution</label>
                        <textarea name="solution" cols="100"></textarea>
                        {!! Form::submit('Ajouter',['class'=>'btn btn-block']) !!}
                    </fieldset>
                    {!! Form::close() !!}
                </div>
            </div>
        </div><!-- /content -->
    </div><!-- /page -->
    <script>
        function changedType() {
            const type = $('#type').val();
            console.log('changed type', type);
            if (type == 1) {
                $('#mauvais').removeAttr('disabled');
            } else {
                $('#mauvais').val('0');
                $('#mauvais').attr('disabled','disabled');
            }
        }
    </script>
@stop

resources/views/questionnaires/edit.blade.php
@extends('layout.dashboard')
@section('section')
    <div><!-- page -->
        <nav class="top-bar clearfix">
            <div class="container-fluid clearfix">
                <a class="top-bar-brand" href="#">
                    <span class="atosIconFont atosIconFont-logo"></span>
                </a>
                <!-- <span>Production</span> -->
            </div>
        </nav>
        <div class="clearfix contentsso pki" role="main" style="margin-top: 105.25px;"><!-- content -->
            <div class="clearfix sso-box">
                <div class="wg-pki">
                    {{Form::model($questionnaire,[
                        'method'=>'patch',
                    'route'=>['questionnaire.update',$questionnaire->id]
                         ])}}
                    <fieldset>
                        <label>Titre</label>
                        <select name="title"  value="{{$questionnaire->title}}" required >
                            <option selected="selected" value="{{$questionnaire->title}}">
                            {{$questionnaire->title}} </option>
                            <option value="Bureautique">Bureautique</option>
                            <option value="Acces Atos">Acces Atos</option>
                            <option value="Acces WL">Acces wl</option>
                            <option value="lenteur">Lenteur</option>
                            <option value="Boite Mail">Configuration boite WL</option>
                            <option value="autres">Autres</option>
                        </select>
                        <br>

                        <label>Type</label>
                        <select name="type" required value="{{$questionnaire->type}}">
                            <option selected="selected" value="{{$questionnaire->type}}"> @if($questionnaire->type == 1) question ferme @else question ouverte @endif </option>
                            <option value="1">Question ferme</option>
                            <option value="0">Question ouverte </option>
                        </select>
                        <br>
                        <label>Réponse problematique (A afficher) </label>
                        <select name="mauvais" id="mauvais" value="{{$questionnaire->mauvais}}" required>
                            <option selected="selected" value="{{$questionnaire->mauvais}}"> @if($questionnaire->mauvais == 1) Oui @else Non @endif </option>
                            <option  @if($questionnaire->mauvais == 1) selected @endif value="1">Oui</option>
                            <option  @if($questionnaire->mauvais == 0) selected="selected" @endif value="0">Non</option>
                        </select>
                        <br>

                        <label>Contenu</label>
                        <input type="text" name="content" style="width: 50%" value="{{$questionnaire->content}}" required>
                        <br>
                        <label>Solution</label>
                        <textarea name="solution" cols="100">{{$questionnaire->solution}}</textarea>
                        {!! Form::submit('Enregistrer',['class'=>'btn btn-block']) !!}
                    </fieldset>
                    {!! Form::close() !!}
                </div>
            </div>
        </div><!-- /content -->
    </div><!-- /page -->
    <script>
        function changedType() {
            const type = $('#type').val();
            console.log('changed type', type);
            if (type == 1) {
                $('#mauvais').removeAttr('disabled');
            } else {
                $('#mauvais').val('0');
                $('#mauvais').attr('disabled','disabled');
            }
        }
    </script>

@stop

resources/views/questionnaires/index.blade.php
@extends('layout.dashboard')
@section('section')
    @if (Sentinel::check() && Sentinel::getUser()->roles()->first()->slug == 'admin')
    <div class="container-fluid">
        <hr>
        <div class="row-fluid">
            <div class="span12">
                <a class="btn btn-primary icon-plus-sign pull-right" href="{{route('questionnaire.create')}}">Nouvelle question</a>
                <div class="widget-box">
                    <div class="widget-title"><span class="icon"> <i class="icon-th"></i> </span>
                        <h5><u>Questionnaires</u></h5>
                    </div>
                    <div class="widget-content nopadding">
                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Titre</th>
                                <th>Contenu</th>
                                <th>Réponse Problématique</th>
                                <th>Solution</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                            @foreach($questionnaires as $questionnaire)
                                <tbody>
                                <tr class="odd gradeX">
                                    <td>{{$questionnaire->title}}</td>
                                    <td>
                                        {{$questionnaire->content}}
                                    </td>
                                    <td>@if($questionnaire->mauvais == 1) Oui @else Non @endif</td>
                                    <td>{!!$questionnaire->solution!!}</td>
                                    <td>
                                        <a href="#myAlert{{$questionnaire->id}}" data-toggle="modal"
                                           class="btn btn-danger btn-mini">Supprimer</a>
                                        <a class="btn btn-info btn-mini" href="{{route('questionnaire.edit',$questionnaire->id)}}">Modifier</a>
                                        {{-- <a class="btn btn-info btn-mini" href="{{route('questionnaire.show',$questionnaire->id)}}">Solution</a> --}}
                                        <div id="myAlert{{$questionnaire->id}}" class="modal " style="width: fit-content ; background-color: white;position: fixed; margin-left: auto">
                                            <div class="modal-header">
                                                <button data-dismiss="modal" class="close" type="button">×</button>
                                                <h3>Attention</h3>
                                            </div>
                                            <div class="modal-body">
                                                <p>Voulez vous vraiment supprimer cette question </p>
                                            </div>
                                            <div class="modal-footer">
                                                {{Form::open([
                                                'method'=>'DELETE',
                                                'route'=>['questionnaire.destroy',$questionnaire->id] ])}}
                                                {{Form::button('Confirmer', array('type' => 'submit', 'class' => 'btn btn-primary'))}}
                                                <a data-dismiss="modal" class="btn" href="#">Cancel</a></div>
                                            {{Form::close()}}
                                        </div>

                                    </td>
                                </tr>
                                </tbody>
                            @endforeach
                        </table>
                        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
                    </div>
                </div>

            </div>
        </div>
    </div>
    @else
        questionnaires
    @endif
@stop