routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'role'], function () {
    Route::get('/', function() {
        return redirect('/home');
    });
});

Route::get('/signin', function () {
    return view('auth.login');
});


Route::resource('login', 'LoginController');



Route::get('logout', 'LoginController@logout')->name('logout');

//Route::get('/earnings','AdminController@earnings');



Route::group(['middleware' => 'admin'], function () {
    Route::get('/register','RegistrationController@register')->name('register');
    Route::post('register', 'RegistrationController@store')->name('register.store');
    Route::resource('role', RoleController::class);
    Route::resource('tutoriel', TutorielController::class);
    Route::resource('questionnaire', QuestionnairesController::class);
    Route::get('reponse','ReponseController@index')->name('reponse.index');
    Route::post('supprimer/{id}','ReponseController@destroy')->name('reponse.destroy');
    Route::post('reponse/users','ReponseController@show')->name('reponse.show');
    Route::post('reponse/stat/search','ReponseController@showstat')->name('reponse.showstat');
    Route::post('reponse/heureU','ReponseController@showHeureAndU')->name('reponse.showHeureAndU');
    Route::get('reponse/stat','ReponseController@stat')->name('reponse.stat');
    route::get('user','usersController@lists')->name('listusers');
    Route::post('supp/{id}','AdminController@destroy')->name('admin.destroy');
    Route::post('resetP','AdminController@resetP')->name('resetP');
    Route::resource('solution', SolutionController::class);
});

Route::group(['middleware' => 'users'], function () {
    Route::get('/changePassword','usersController@changePassword')->name('changePassword');
    Route::get('/home','usersController@home')->name('home');
    Route::post('/Password','usersController@Password')->name('Password');
    Route::resource('users', 'usersController');
    Route::post('update/','ReponseController@update')->name('reponse.update');
    Route::post('users','ReponseController@store')->name('reponse.store');
    Route::get('/tutoriels', 'TutorielController@list');
    Route::get('/tutoriels/{id}', 'TutorielController@show')->name('tutoriels.view');
});

resources/views/layout/partials/navbar_head.blade.php
<div id="header">
    <h1><a href=""> @yield('title')</a></h1>
</div>

resources/views/layout/partials/navbar_static_side.blade.php
<div class="col-md-3 left_col" style="position: fixed;" >
    <div class="left_col scroll-view">
        <div class="navbar nav_title" >
            <a href="#" class="site_title"><img src="{{asset("assets/image/Atos-Logo.png")}}" alt="" width="170" height="70"></a>
        </div>
        <div class="clearfix"></div>

        <br/>
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>General</h3>


                    @if (Sentinel::check() && Sentinel::getUser()->roles()->first()->slug == 'admin')
                    <ul class="nav side-menu">

                    <li><a href="{{route('role.index')}}"><i class="fa fa-edit"></i> Roles</a></li>

                    <li><a><i class="fa fa-desktop"></i> Collaborateurs <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{route('listusers')}}"> Liste des Collaborateurs</a></li>
                            <li><a href="{{route('reponse.index')}}"> Collaborateurs ayant répondu</a></li>
                            <li><a href="{{route('reponse.stat')}}"> Statistiques</a></li>
{{--                            <li><a href="#"> Collaborateurs n'ayant pas répondu</a></li>--}}
                        </ul>
                    </li>
                        <li><a><i class="fa fa-desktop"></i> Questionnaire <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li><a href="{{route('questionnaire.index')}}">liste questionaires</a></li>
{{--                                <li><a href="#"> Bonnes Pratiques</a></li>--}}
                            </ul>
                        </li>
                        <li><a><i class="fa fa-desktop"></i> Tutoriels <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li><a href="{{route('tutoriel.index')}}">Liste des Tutoriels</a></li>
{{--                                <li><a href="#"> Bonnes Pratiques</a></li>--}}
                            </ul>
                        </li>
                        <!--<li><a><i class="fa fa-desktop"></i> solutions <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li><a href="{{route('solution.index')}}">liste solutions</a></li>
                                {{--                                <li><a href="#"> Bonnes Pratiques</a></li>--}}
                            </ul>
                        </li>-->
                        <li><a href="{{route('register')}}"><i class="fa fa-clone"></i> Ajouter un collaborateur</a></li>
                </ul>
                    @else
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <!-- <li><a href="{{route('home')}}#Bonnes_Pratiques">Bonnes Pratiques</a></li> -->
                                    <li><a href="{{route('home')}}#Solution">Solutions</a></li>
                                    <li><a href="{{route('home')}}#Autres">Autres...</a></li>
                                    <li><a href="{{route('home')}}#Qestions_ouvertes">Qestions ouvertes</a></li>
                                </ul>
                            </li>
                    <li><a><i class="fa fa-desktop"></i> Questionnaire <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{route('users.index')}}#Bureautique">Bureautique</a></li>
                            <li><a href="{{route('users.index')}}#Acces Atos">Acces Atos</a></li>
                            <li><a href="{{route('users.index')}}#Acces WL">Acces WL</a></li>
                            <li><a href="{{route('users.index')}}#Lenteurs">Lenteurs</a></li>
                            <li><a href="{{route('users.index')}}#Boite Mail">Configuration boite WL</a></li>
                             <li><a href="{{route('users.index')}}#submit_button">Envoyer formulaire</a></li>

                        </ul>
                    </li>
                            <li><a href="tutoriels"><i class="fa fa-youtube-play"></i> Tutoriels</a></li>
                        </ul>
                    @endif


            </div>


        </div>

        <br/>
    </div>
</div>

resources/views/layout/partials/navbar_top.blade.php
<div class="top_nav navbar-fixed-top " style="position: fixed;top: 0; ">
    <div class="nav_menu">
        <nav class="" role="navigation">
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        @if (Sentinel::check() && Sentinel::getUser()->roles()->first()->slug == 'admin')
                        <img src="{{asset("assets/img/img.jpg")}}" alt="">Administrateur
                        @else
                            <img src="{{asset("assets/img/img.jpg")}}" alt="">Collaborateur
                        @endif
                            <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="{{route('logout')}}"><i class="fa fa-sign-out pull-right"></i> Déconnexion</a></li>
                        @if (Sentinel::check() && Sentinel::getUser()->roles()->first()->slug == 'users')
                        <li><a href="{{ route('changePassword') }}"><i class="fa fa-edit pull-right"></i> Modifier mot de passe</a></li>
                        @endif
                    </ul>
                </li>

            </ul>
        </nav>
    </div>
</div>